apiVersion: v1
kind: Service
metadata:
  name: investutil-back
spec:
  selector:
    app: investutil-back
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP 